### ISSUE TITLE
Dataroot error

### ISSUE THREAD

**Issue by ilnehc** [qcraftai/tip#2]
Thanks for the great work. 
https://github.com/qcraftai/tip/blob/b4b984aeecc0f5fcebbb29f6d58aa7359c7bda00/trans_idealism_planner/explore.py#L308
https://github.com/qcraftai/tip/blob/b4b984aeecc0f5fcebbb29f6d58aa7359c7bda00/trans_idealism_planner/explore.py#L362
Here, the `dataroot` should be the input `dataroot`, without the version str. The version is joined when the NuScenes is initialized which will cause no file error.

**Comment by weixinli018** [comment]
@ilnehc Thank you reporting this issue. We have fixed the problem. Please let us know other issues if you spot any.
